protocol: PBFT
batching:
  batch_size: 10
  batch_timer_ms: 50
timers:
  view_change_ms: 8000
metrics:
  window_size: 100
agents:
  1: 50200
  2: 50201
  3: 50202
  4: 50203
phases:
  Request:
    quorum: 1
    next_state: PrePrepare
    actions:
      - verifySignature:
          public_key: "../keys/${client_id}_public.pem"
      - "handleClientRequestAsLeader"
  PrePrepare:
    quorum: 1
    next_state: prepare
    actions:
      - "startTimer"
      - "storeMessage"
      - verifySignature:
          public_key: "../keys/server_${client_id}_public.pem"
      - "verifyPBFTConditions"
      - "broadcast"
  prepare:
    quorum: 2f
    next_state: commit
    actions:
      - "storeMessage"
      - "checkQuorum"
      - "resetTimer"
      - "broadcast"
  commit:
    quorum: 2f
    next_state: Request
    actions:
      - "storeMessage"
      - "checkQuorum"
      - "stopTimer"
      - "complete"
  ViewChange:
    quorum: 2f
    next_state: Request
    actions:
      - "handleViewChange"
  NewView:
    quorum: 1
    next_state: Request
    actions:
      - "handleNewView"

  QueryBalances:
    quorum: 1
    next_state: Request
    actions:
      - "queryBalances"
