entities:
  - id: 1
    role: Leader
    byzantine: false
    peers: [1, 2, 3, 4]
    cluster: 0
  - id: 2
    role: Replica
    byzantine: false
    peers: [1, 2, 3, 4]
    cluster: 0
  - id: 3
    role: Replica
    byzantine: false
    peers: [1, 2, 3, 4,]
    cluster: 0
  - id: 4
    role: Replica
    byzantine: false
    peers: [1, 2, 3, 4]
    cluster: 0
delays:
