protocol: SBFT
metrics:
  window_size: 100
batching:
  batch_size: 10
  batch_timer_ms: 50
timers:
  view_change_ms: 8000
  fast_path_wait_ms: 20
agents:
  1: 50100
  2: 50101
  3: 50102
  4: 50103
phases:
  Request:
    quorum: 1
    next_state: PrePrepare
    actions:
      - verifySignature:
          public_key: "../keys/${client_id}_public.pem"
      - "handleClientRequestAsLeader"
  PrePrepare:
    quorum: 1
    next_state: prepare
    actions:
      - "storeMessage"
      - "startTimer"
      - "verifyPBFTConditions"
      - "unicastifParticipant"
  prepare:
    quorum: 2f
    next_state: commit
    actions:
      - "storeMessage"
      - "checkQuorumForSBFT"
      - "resetTimer"
      - "broadcastifLeader"
      - "unicastifParticipant"
  commit:
    quorum: 2f
    next_state: Request
    actions:
      - "storeMessage"
      - "checkQuorumForSBFT"
      - "stopTimer"
      - "broadcastifLeader"
      - "complete"
  ViewChange:
    quorum: 2f
    next_state: Request
    actions:
      - "handleViewChange"
  NewView:
    quorum: 1
    next_state: Request
    actions:
      - "handleNewView"
  QueryBalances:
    quorum: 1
    next_state: Request
    actions:
      - "queryBalances"
