protocol: Zyzzyva
timers:
  view_change_ms: 6000
  fast_path_wait_ms: 50
metrics:
  window_size: 100
agents:
  1: 50100
  2: 50101
  3: 50102
  4: 50103
phases:
  Request: 
    quorum: 1
    next_state: SpeculativeExecute
    actions:
      - verifySignature:
          public_key: "../keys/${client_id}_public.pem"
      - "handleClientRequestAsLeader"
  SpeculativeExecute:
    quorum: 1
    next_state: Request
    actions:
      - "storeMessage"
      - "speculativeComplete"
  Commit:
    quorum: 1
    next_state: Request
    actions:
      - "commitCertificate"

  ViewChange:
    quorum: 2f+1
    next_state: NewView
    actions:
      - "zyzzyvaViewChange"

  NewView:
    quorum: 1
    next_state: Request
    actions:
      - "zyzzyvaHandleNewView"

  QueryBalances:
    quorum: 1
    next_state: Request
    actions:
      - "queryBalances"

